service: url-shortener

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
custom:
  customDomain:
    domainName: ${self:custom.domainName}
    certificateName: '*.rafaaudibert.dev'
    createRoute53Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: false
  domainName: url.rafaaudibert.dev

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  env:
    MONGO_URI: ${env:MONGO_URI}
    MONGO_DATABASE: ${env:MONGO_DATABASE}
    MONGO_COLLECTION: ${env:MONGO_COLLECTION}
    SECRET: ${env:SECRET}
    
functions:
  shorten:
    name: ${self:service}-shorten-${self:provider.stage}
    handler: src/handlers/shorten.handler
    events:
      - http:
          method: post
          path: /s
          cors: true
  redirect:
    name: ${self:service}-redirect-${self:provider.stage}
    handler: src/handlers/redirect.handler
    events:
      - http:
          method: get
          path: /r/{url}
          cors: true
          request:
            parameters:
              paths:
                url: true

