name: Deploy URL Shortener
on:
  push:
    branches:
      - master
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
        aws-region: us-east-1
    - name: Install dependencies
      run: npm install
    - name: Deploy lambda
      run: npm run deploy